---
- name: Ejecutar script SQL usando SQL*Plus
  shell: $ORACLE_HOME/bin/sqlplus -S {{ item.oracle_user }}/{{ item.oracle_password }}@localhost:{{ item.oracle_port }}/{{ item.oracle_database }} @{{ item.script_sql_path }}
  environment: 
    ORACLE_HOME: "{{ item.variable_home }}"
    LD_LIBRARY_PATH: "{{ item.ld_path }}"
    PATH: "{{ item.path_bin }}"
  register: sqlplus_output
  loop: "{{ servers_and_databases }}"
  
  
- name: Mostrar salida de SQL*Plus
  debug:
    var: sqlplus_output.stdout_lines
